project_id = "raenkewzlvrdqufwxjpl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.business-lookup]
verify_jwt = false