# California Statement of Information Filing Task Template
# This TASK TEMPLATE (not agent) contains California-specific business logic
# Version: 1.0.0

# Task Template Identity
templateId: "soi-filing-california"
templateType: "compliance_filing"
version: "1.0.0"
name: "California Statement of Information Filing"
description: "Task template for filing Statement of Information with California Secretary of State"

# Jurisdiction-Specific Configuration
jurisdiction:
  state: "CA"
  country: "US"
  agency: "California Secretary of State"
  website: "https://businesssearch.sos.ca.gov"

# Entity-Specific Requirements
entityRequirements:
  LLC:
    filingFrequency: "biennial"
    dueDate: "Every 2 years by last day of registration month"
    fee: 20
    formNumber: "LLC-12"
    requiredFields:
      - "principal_office_address"
      - "members_managers_list"
      - "registered_agent"
  
  Corporation:
    filingFrequency: "annual"
    dueDate: "Anniversary of incorporation"
    fee: 25
    formNumber: "SI-100"
    requiredFields:
      - "principal_executive_office"
      - "officers_list"
      - "directors_list"
      - "registered_agent"

# Workflow Phases
phases:
  - id: "eligibility_check"
    name: "Eligibility Verification"
    requiredAgents:
      - "DataEnrichmentAgent"  # To look up business data
      - "ProfileBuilderAgent"  # To assemble business profile
    steps:
      - "Verify entity is registered in California"
      - "Check entity type (LLC vs Corporation)"
      - "Calculate filing deadline"
  
  - id: "data_collection"
    name: "Information Gathering"
    requiredAgents:
      - "ProfileBuilderAgent"  # To track completeness
    dataRequired:
      - businessName
      - entityNumber
      - registeredAgent
      - principalAddress
      - officers  # For corporations
      - members   # For LLCs
  
  - id: "form_preparation"
    name: "Form Preparation"
    requiredAgents:
      - "ProfileBuilderAgent"  # To validate data
    outputs:
      - "completed_form_data"
      - "validation_report"
  
  - id: "submission"
    name: "Filing Submission"
    requiredAgents:
      - "BackendOrchestratorAgent"  # To coordinate submission
    actions:
      - "Generate filing documents"
      - "Calculate fees"
      - "Submit to SOS portal"

# Validation Rules (California-specific)
validationRules:
  registeredAgent:
    mustBeInCalifornia: true
    requiresPhysicalAddress: true
    cannotBePOBox: true
  
  principalAddress:
    allowOutOfState: true
    requiresStreetAddress: true
  
  officers:
    minimumRequired:
      CEO: 1
      Secretary: 1
      CFO: 1
  
  members:
    minimumRequired: 1
    requiresPercentageOwnership: true

# Compliance Deadlines
deadlines:
  LLC:
    initialFiling: "90 days from registration"
    subsequentFilings: "Every 2 years by last day of registration anniversary month"
    gracePeriod: "60 days"
    penalty: "$250 late fee"
  
  Corporation:
    initialFiling: "90 days from incorporation"
    subsequentFilings: "Annually during anniversary month"
    gracePeriod: "None"
    penalty: "$250 late fee"

# UI Configuration for Data Collection
uiConfiguration:
  forms:
    - id: "business_info"
      title: "Business Information"
      fields:
        - name: "businessName"
          type: "text"
          label: "Legal Business Name"
          required: true
        - name: "entityNumber"
          type: "text"
          label: "California Entity Number"
          pattern: "^[C]\\d{7}$"
          help: "Format: C1234567"
    
    - id: "registered_agent"
      title: "Registered Agent Information"
      fields:
        - name: "agentName"
          type: "text"
          label: "Registered Agent Name"
        - name: "agentAddress"
          type: "address"
          label: "California Street Address"
          validation: "california_address"

# Notification Templates
notifications:
  upcomingDeadline:
    trigger: "30 days before due date"
    message: "Your California Statement of Information is due on {dueDate}"
  
  overdue:
    trigger: "1 day after due date"
    message: "Your SOI filing is overdue. Late fee of $250 will apply."