id: soi-filing
name: California Statement of Information Filing
description: Complete and submit Statement of Information to California Secretary of State
category: compliance
priority: high
estimatedDuration: 60
requiredAgents:
  - orchestrator
  - legal_compliance
  - data_collection
  - payment
  - agency_interaction
  - monitoring
  - communication
requiredTools:
  - ca-sos-portal
  - quickbooks
  - plaid
  - document-generator
  - form-validator

steps:
  - id: validate_requirements
    name: Validate SOI Requirements
    agent: legal_compliance
    action: validate_soi_requirements
    inputs:
      checkDeadline: true
      verifyBusinessType: true
    outputs:
      - isRequired
      - dueDate
      - fee
      - formNumber
    errorHandling:
      retryCount: 2
      fallbackAction: manual_review
      escalationAgent: orchestrator

  - id: collect_business_data
    name: Collect Business Information
    agent: data_collection
    action: collect_business_data
    inputs:
      sources:
        - quickbooks
        - manual_entry
      dataPoints:
        - business_name
        - file_number
        - business_address
        - mailing_address
        - officer_information
        - member_information
        - agent_for_service
    outputs:
      - businessData
      - dataValidated
    conditions:
      pre:
        - requirements_validated
    errorHandling:
      retryCount: 3
      fallbackAction: request_manual_input
      escalationAgent: communication

  - id: prepare_form
    name: Prepare SOI Form
    agent: legal_compliance
    action: prepare_compliance_form
    inputs:
      formType: SOI
      businessData: "${businessData}"
    outputs:
      - preparedForm
      - validationResult
    conditions:
      pre:
        - data_collected
        - data_validated

  - id: user_approval
    name: Request User Approval
    agent: communication
    action: request_approval
    inputs:
      document: "${preparedForm}"
      message: "Please review and approve your Statement of Information before submission"
      timeout: 86400
    outputs:
      - approved
      - corrections
    conditions:
      pre:
        - form_prepared

  - id: process_payment
    name: Process Filing Fee
    agent: payment
    action: process_soi_payment
    inputs:
      amount: "${fee}"
      paymentMethod: default
      description: "CA Statement of Information Filing Fee"
    outputs:
      - paymentConfirmation
      - transactionId
    conditions:
      pre:
        - user_approved
    errorHandling:
      retryCount: 3
      fallbackAction: alternate_payment_method
      escalationAgent: communication

  - id: submit_form
    name: Submit to CA SOS
    agent: agency_interaction
    action: submit_soi_form
    inputs:
      portal: CA_SOS
      form: "${preparedForm}"
      paymentConfirmation: "${paymentConfirmation}"
    outputs:
      - submissionId
      - confirmationNumber
      - receiptUrl
    conditions:
      pre:
        - payment_completed
    errorHandling:
      retryCount: 5
      fallbackAction: manual_submission
      escalationAgent: orchestrator

  - id: track_status
    name: Track Submission Status
    agent: monitoring
    action: track_submission
    inputs:
      submissionId: "${submissionId}"
      checkInterval: 3600
      maxChecks: 48
    outputs:
      - finalStatus
      - processingTime

  - id: notify_completion
    name: Notify User of Completion
    agent: communication
    action: send_completion_notification
    inputs:
      taskId: "${taskId}"
      confirmationNumber: "${confirmationNumber}"
      receiptUrl: "${receiptUrl}"
      nextDeadline: "${nextYearDeadline}"
    conditions:
      pre:
        - submission_confirmed

dataRequirements:
  - field: business_name
    type: string
    required: true
    validation: "^[A-Za-z0-9 ,.'&-]+$"
  
  - field: file_number
    type: string
    required: true
    source: CA_SOS
    validation: "^[A-Z0-9]{7,12}$"
  
  - field: business_address
    type: object
    required: true
    validation: valid_ca_address
  
  - field: officer_information
    type: array
    required: true
    validation: min_one_officer
  
  - field: agent_for_service
    type: object
    required: true
    validation: valid_agent_info

deadlineRules:
  type: recurring
  value: annually
  alertThreshold: 30

compliance:
  jurisdiction: California
  formNumber: SI-200/LLC-12
  regulatoryBody: California Secretary of State
  penalties: "$250 penalty after 60 days delinquent"