id: test_template
name: Test Template
version: 1.0.0
description: Test template for unit tests
task_type: test
priority: low
metadata:
  test: true
phases:
  - id: test_phase
    name: Test Phase
    description: Test phase for unit tests
    agents:
      - TestAgent
    steps:
      - id: step1
        name: Test Step
        description: Test step
        agent: TestAgent
        action: test_action
fields:
  - id: test_field
    name: Test Field
    type: string
    required: false
ui_components:
  - type: form
    id: test_form
    fields:
      - test_field
dependencies: []
validations: []
hooks:
  onStart: []
  onComplete: []
  onError: []