# SOI Specialist Agent Configuration
# Updated for BaseAgent A2A Protocol Architecture
# Version: 2.0.0

# Agent Identity and Role
name: "SOISpecialistAgent"
role: "soi_specialist"
version: "2.0.0"
description: "Specialist agent for California Statement of Information filing compliance"

# Agent Capabilities - WHAT it can do
capabilities:
  - "soi_filing_assistance"
  - "california_business_compliance"
  - "document_validation"
  - "deadline_tracking"
  - "filing_instruction_generation"
  - "data_requirements_analysis"

# Tool Requirements - WHAT tools it needs
toolRequirements:
  - "web_search"
  - "data_validation"
  - "document_processing"
  - "ca_sos_search"

# A2A Protocol Configuration
a2a:
  protocolVersion: "1.0.0"
  communicationMode: "async"
  messageFormats:
    - "json"
    - "yaml"
  
  # Inter-agent communication settings
  routing:
    canReceiveFrom:
      - "TaskOrchestrator"
      - "ComplianceAgent"
      - "DataValidationAgent"
      - "ProfileBuilderAgent"
    canSendTo:
      - "TaskOrchestrator"
      - "UIGeneratorAgent"
      - "NotificationAgent"
      - "DocumentGeneratorAgent"
  
  # Message handling
  messageHandling:
    bufferSize: 50
    timeoutMs: 15000
    retryEnabled: true

# Task Execution Configuration
execution:
  maxConcurrentTasks: 2
  timeoutMs: 45000
  
  retryStrategy:
    maxRetries: 3
    backoffMs: 1000
    exponentialBackoff: true
  
  # Performance settings
  performance:
    cachingEnabled: true
    cacheExpiryMs: 600000  # 10 minutes
    batchProcessing: false

# Context and State Management
context:
  persistence: true
  shareLevel: "task"  # private | task | global
  
  # What context keys this agent manages
  contextKeys:
    - "soiFilingData"
    - "complianceDeadlines"
    - "filingValidation"
    - "userGuidance"
  
  # Context transformation rules
  transformations:
    - input: "userInput.businessName"
      output: "soiFilingData.entityName"
      validation: "required|string|min:2"
    
    - input: "userInput.entityType"
      output: "soiFilingData.entityType"
      validation: "required|enum:LLC,Corporation,Partnership"

# UI Augmentation Settings
ui:
  enableAugmentation: true
  
  augmentationTypes:
    - "form_generation"
    - "validation_messages"
    - "deadline_alerts"
    - "filing_instructions"
    - "help_tooltips"
  
  progressReporting: true
  
  # UI generation rules
  formGeneration:
    soiFilingForm:
      title: "California Statement of Information"
      description: "Complete your required SOI filing"
      
      fields:
        - field: "entityName"
          label: "Entity Name"
          type: "text"
          required: true
          validation: "required|string|min:2|max:200"
          help: "The exact legal name of your business entity"
        
        - field: "entityType"
          label: "Entity Type"
          type: "select"
          required: true
          options:
            - value: "LLC"
              label: "Limited Liability Company (LLC)"
            - value: "Corporation"
              label: "Corporation"
            - value: "LP"
              label: "Limited Partnership"
          help: "Select your business entity structure"
        
        - field: "filingDueDate"
          label: "Filing Due Date"
          type: "date"
          required: true
          help: "When your SOI filing is due"
        
        - field: "principalAddress"
          label: "Principal Executive Office Address"
          type: "address"
          required: true
          help: "Primary business address in California"
      
      quickActions:
        - id: "validate_info"
          label: "Validate information"
          action: "validate_soi_data"
          icon: "check"
        
        - id: "filing_help"
          label: "Get filing help"
          action: "show_filing_instructions"
          data: { topic: "soi_filing_process" }
          icon: "help"

# Workflow and Task Definitions
workflows:
  soiFilingAssistance:
    description: "Guide user through SOI filing process"
    
    steps:
      - name: "analyze_requirements"
        action: "determine_soi_requirements"
        required: true
        
      - name: "validate_data"
        action: "validate_filing_data"
        fallback: "request_missing_info"
        
      - name: "generate_instructions"
        action: "create_filing_instructions"
        
      - name: "track_deadline"
        action: "setup_deadline_monitoring"
    
    outputs:
      - "soiFilingData.requirements"
      - "soiFilingData.validationStatus"
      - "soiFilingData.filingInstructions"

  dataValidation:
    description: "Validate SOI filing data for compliance"
    
    steps:
      - name: "format_validation"
        action: "check_data_formats"
        
      - name: "completeness_check"
        action: "verify_required_fields"
        
      - name: "compliance_verification"
        action: "validate_california_requirements"
        
      - name: "generate_report"
        action: "create_validation_report"
    
    outputs:
      - "validation.formatCheck"
      - "validation.completenessScore"
      - "validation.complianceStatus"

# Agent Prompt Templates (Legacy Compatibility)
prompts:
  main:
    version: "2.0"
    template: |
      You are a California SOI (Statement of Information) filing specialist.
      
      Current filing status:
      Business Name: {{business_name}}
      Entity Type: {{entity_type}}
      Filing Due: {{due_date}}
      Last Filed: {{last_filed}}
      
      User Query: {{message}}
      
      Current Data Completeness:
      {{data_status}}
      
      Provide helpful guidance for SOI filing. Focus on:
      1. What information is still needed
      2. Common mistakes to avoid
      3. Filing deadlines and penalties
      4. Step-by-step assistance
      
      Be concise but thorough. Use encouraging tone.
    
  data_requirements:
    version: "2.0"
    template: |
      Identify required SOI data fields for {{entity_type}} in California.
      
      Already collected:
      {{collected_fields}}
      
      Return JSON array of missing required fields with:
      - field_name
      - field_type
      - description
      - is_required
      - validation_rules
    
  validation:
    version: "2.0"
    template: |
      Validate SOI data for filing compliance.
      
      Entity Type: {{entity_type}}
      Data: {{form_data}}
      
      Check for:
      1. Required fields completeness
      2. Format validity (addresses, dates, etc.)
      3. Logical consistency
      4. California-specific requirements
      
      Return validation result with specific issues if any.
    
  filing_instructions:
    version: "2.0"
    template: |
      Provide step-by-step SOI filing instructions.
      
      Entity: {{entity_type}}
      Filing Type: {{filing_type}}
      User Experience Level: {{experience_level}}
      
      Create clear, numbered steps for completing the filing.
      Include tips and warnings for each step.

# Error Handling and Monitoring
errorHandling:
  logLevel: "info"
  
  criticalErrors:
    - "data_validation_failed"
    - "deadline_calculation_error"
    - "ca_sos_api_unavailable"
  
  retryableErrors:
    - "network_timeout"
    - "rate_limit_exceeded"
    - "temporary_service_unavailable"
  
  fallbackActions:
    - error: "ca_sos_search_failed"
      fallback: "use_manual_verification"
    
    - error: "validation_service_down"
      fallback: "use_basic_validation"

# Monitoring and Analytics
monitoring:
  enabled: true
  
  metrics:
    - "filing_assistance_completion_rate"
    - "validation_accuracy"
    - "user_satisfaction"
    - "deadline_tracking_success"
  
  alerts:
    - condition: "completion_rate < 0.8"
      action: "notify_admin"
      severity: "high"

# Integration Settings
integrations:
  # California Secretary of State API
  californiaSOSAPI:
    enabled: true
    rateLimit: 60  # per hour
    timeout: 8000
    
  # Document generation
  documentGenerator:
    enabled: true
    templates: ["soi_form", "instruction_guide"]

# Development and Testing
development:
  debugMode: false
  verboseLogging: false
  
  testData:
    sampleEntityName: "Sample Business LLC"
    sampleEntityType: "LLC"
    sampleDueDate: "2024-07-31"
  
  mockServices:
    enabled: false
    responseDelay: 1000