# Force Node.js detection
[providers]
node = "18.17.0"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]  
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"