[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["railway/**"]

[build.env] 
NODE_VERSION = "18"
NODE_ENV = "production"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10