# ============================================================================
# STATEMENT OF INFORMATION (SOI) FILING TEMPLATE
# PRD Lines 589-699: Task Template Structure
# 
# This template orchestrates the complete SOI filing workflow
# Demonstrates multi-agent coordination and progressive disclosure
# ============================================================================

task_template:
  id: "soi_filing"
  version: "1.0.0"
  
  # PRD Lines 594-599: Metadata
  metadata:
    name: "California Statement of Information Filing"
    description: "Annual/Biennial SOI filing with CA Secretary of State"
    category: "compliance"
    estimatedDuration: 600  # 10 minutes
    priority: "high"
    deadline_type: "recurring"
  
  # PRD Lines 601-618: Declarative goals
  goals:
    primary:
      - id: "verify_filing_requirement"
        description: "Determine if SOI is due and type required"
        required: true
        
      - id: "collect_current_info"
        description: "Gather current business information"
        required: true
        
      - id: "prepare_soi_form"
        description: "Complete SOI form with validated data"
        required: true
        
      - id: "submit_to_ca_sos"
        description: "Submit form to California Secretary of State"
        required: true
        
      - id: "verify_acceptance"
        description: "Confirm filing was accepted"
        required: true
    
    secondary:
      - id: "update_business_records"
        description: "Update internal records with new filing"
        required: false
        
      - id: "schedule_next_filing"
        description: "Set reminder for next SOI deadline"
        required: false
  
  # PRD Lines 621-631: State machine
  states:
    allowed:
      - "created"
      - "checking_requirements"
      - "gathering_data"
      - "validating_info"
      - "preparing_form"
      - "awaiting_payment"
      - "submitting"
      - "pending_confirmation"
      - "completed"
      - "failed"
      - "rejected"
    
    initial: "created"
    terminal: ["completed", "failed", "rejected"]
    
    transitions:
      created: ["checking_requirements"]
      checking_requirements: ["gathering_data", "completed"]
      gathering_data: ["validating_info"]
      validating_info: ["preparing_form", "gathering_data"]
      preparing_form: ["awaiting_payment"]
      awaiting_payment: ["submitting"]
      submitting: ["pending_confirmation", "rejected"]
      pending_confirmation: ["completed", "rejected"]
      rejected: ["gathering_data", "failed"]
  
  # PRD Lines 634-648: Phases of execution
  phases:
    - id: "requirement_check"
      description: "Verify SOI filing requirements"
      prerequisites: []
      next: ["data_collection"]
      agents: ["legal_compliance"]
      
    - id: "data_collection"
      description: "Gather business information from multiple sources"
      prerequisites: ["requirement_check"]
      next: ["validation"]
      agents: ["data_collection", "public_records"]
      
    - id: "validation"
      description: "Validate and reconcile collected data"
      prerequisites: ["data_collection"]
      next: ["form_preparation"]
      agents: ["legal_compliance"]
      
    - id: "form_preparation"
      description: "Prepare SOI form with validated data"
      prerequisites: ["validation"]
      next: ["payment"]
      agents: ["legal_compliance"]
      
    - id: "payment"
      description: "Process filing fee payment"
      prerequisites: ["form_preparation"]
      next: ["submission"]
      agents: ["payment"]
      
    - id: "submission"
      description: "Submit to CA Secretary of State"
      prerequisites: ["payment"]
      next: ["confirmation"]
      agents: ["agency_interaction"]
      
    - id: "confirmation"
      description: "Verify successful filing"
      prerequisites: ["submission"]
      next: ["complete"]
      agents: ["monitoring"]
  
  # PRD Lines 651-678: Data schema
  data_schema:
    type: "object"
    required: ["entity", "filing", "officers", "address"]
    properties:
      entity:
        type: "object"
        required: ["entityNumber", "entityName", "entityType"]
        properties:
          entityNumber:
            type: "string"
            pattern: "^[A-Z0-9-]+$"
            description: "CA SOS Entity Number"
          entityName:
            type: "string"
            minLength: 1
            maxLength: 200
          entityType:
            type: "string"
            enum: ["LLC", "Corporation", "LP", "LLP"]
          jurisdiction:
            type: "string"
            default: "California"
      
      filing:
        type: "object"
        required: ["type", "year", "dueDate"]
        properties:
          type:
            type: "string"
            enum: ["Annual", "Biennial", "Amendment"]
          year:
            type: "integer"
            minimum: 2020
            maximum: 2030
          dueDate:
            type: "string"
            format: "date"
          filingFee:
            type: "number"
            minimum: 20
            maximum: 100
      
      officers:
        type: "array"
        minItems: 1
        items:
          type: "object"
          required: ["name", "title", "address"]
          properties:
            name:
              type: "string"
            title:
              type: "string"
              enum: ["CEO", "President", "Secretary", "CFO", "Managing Member"]
            address:
              type: "object"
              required: ["street", "city", "state", "zip"]
      
      address:
        type: "object"
        required: ["principal", "mailing"]
        properties:
          principal:
            type: "object"
            required: ["street", "city", "state", "zip"]
          mailing:
            type: "object"
            required: ["street", "city", "state", "zip"]
  
  # PRD Lines 680-690: Success criteria
  success_criteria:
    required:
      - "filing.confirmationNumber != null"
      - "filing.status == 'accepted'"
      - "payment.status == 'completed'"
    
    optional:
      - "records.updated == true"
      - "reminder.scheduled == true"
  
  # PRD Lines 693-698: Constraints
  constraints:
    maxDuration: 1800  # 30 minutes
    maxRetries: 3
    requiredAgents:
      - "orchestrator"
      - "legal_compliance"
      - "data_collection"
      - "payment"
      - "agency_interaction"
      - "monitoring"
    
    requiredTools:
      - "ca_sos_portal"
      - "quickbooks_integration"
      - "payment_processor"
      - "document_generator"

# ============================================================================
# AGENT COORDINATION HINTS
# ============================================================================
agent_coordination:
  # Agent roles and responsibilities
  agent_roles:
    legal_compliance:
      responsibilities:
        - "Determine filing requirements based on entity type"
        - "Validate data against CA SOS requirements"
        - "Prepare compliant SOI form"
      
    data_collection:
      responsibilities:
        - "Gather data from QuickBooks"
        - "Extract info from previous filings"
        - "Request missing data from user"
      
    public_records:
      responsibilities:
        - "Search CA SOS for current registration"
        - "Verify entity status"
        - "Find previous SOI filings"
      
    payment:
      responsibilities:
        - "Calculate filing fee"
        - "Process payment via saved method"
        - "Handle payment failures"
      
    agency_interaction:
      responsibilities:
        - "Navigate CA SOS portal"
        - "Submit form electronically"
        - "Download confirmation"
      
    monitoring:
      responsibilities:
        - "Track submission status"
        - "Verify acceptance"
        - "Alert on rejection"
  
  # Inter-agent communication
  communication_flows:
    - from: "orchestrator"
      to: "legal_compliance"
      message: "check_soi_requirements"
      
    - from: "legal_compliance"
      to: "data_collection"
      message: "request_entity_data"
      
    - from: "data_collection"
      to: "public_records"
      message: "verify_registration"
      
    - from: "legal_compliance"
      to: "payment"
      message: "process_filing_fee"
      
    - from: "payment"
      to: "agency_interaction"
      message: "submit_with_payment"
      
    - from: "agency_interaction"
      to: "monitoring"
      message: "track_submission"

# ============================================================================
# PROGRESSIVE DISCLOSURE CONFIGURATION
# ============================================================================
progressive_disclosure:
  # Data collection priority
  collection_order:
    1: "entity.entityNumber"  # Can unlock all CA SOS data
    2: "officers[0].name"     # At least one officer required
    3: "address.principal"    # Required for filing
    
  # Conditional fields
  conditional_requirements:
    officers_count:
      LLC: 1  # Only one managing member needed
      Corporation: 3  # Need CEO, Secretary, CFO
    
    mailing_address:
      show_when: "address.mailing != address.principal"
  
  # Quick actions for common scenarios
  quick_actions:
    - id: "import_quickbooks"
      label: "Import from QuickBooks"
      condition: "quickbooks.connected == true"
      
    - id: "use_previous"
      label: "Use last year's information"
      condition: "previousFiling.exists == true"
      
    - id: "express_filing"
      label: "Express Filing ($50 extra)"
      condition: "filing.dueDate < 7_days"

# ============================================================================
# ERROR HANDLING & RECOVERY
# ============================================================================
error_handling:
  recoverable_errors:
    payment_failed:
      retry: true
      max_retries: 3
      fallback: "request_alternate_payment"
      
    portal_timeout:
      retry: true
      delay: 60  # seconds
      max_retries: 5
      
    validation_failed:
      retry: false
      action: "request_user_correction"
  
  non_recoverable_errors:
    entity_suspended:
      action: "escalate_to_user"
      message: "Entity is suspended. SOI cannot be filed."
      
    invalid_entity_number:
      action: "fail_task"
      message: "Entity number not found in CA SOS."

# ============================================================================
# TODO [POST-MVP] ENHANCEMENTS
# ============================================================================
# TODO: Add batch filing for multiple entities
# TODO: Implement auto-renewal subscription
# TODO: Add predictive filing date suggestions
# TODO: Integrate with calendar for deadline tracking
# TODO: Add multi-state SOI coordination