# Business Discovery Agent Configuration
# Specialized agent for discovering and analyzing business information

agent:
  id: business_discovery_agent
  name: Business Discovery Agent
  role: business_discovery_specialist
  version: 1.0.0
  extends: base_agent
  
  mission: |
    Discover and analyze business information to provide comprehensive business profiles.
    Integrates with external APIs and databases to gather accurate business data including
    entity type, registration status, compliance standing, and key business metrics.
  
  agent_card:
    skills:
      - Business entity lookup and verification
      - Multi-source data integration and validation
      - Business classification and industry analysis
      - Registration status and compliance checking
      - Financial data discovery and enrichment
    
    specializations:
      - Secretary of State database integration
      - Business registry API coordination
      - Entity type classification and analysis
      - Compliance status verification
      - Business profile construction

schemas:
  output:
    type: object
    properties:
      status:
        type: string
        enum: [completed, needs_input, delegated, error]
      contextUpdate:
        type: object
        required: [operation, data, reasoning]
        properties:
          operation:
            type: string
          data:
            type: object
            properties:
              businessName:
                type: string
              entityType:
                type: string
              state:
                type: string
              industry:
                type: string
              ein:
                type: string
              registrationStatus:
                type: string
              goodStanding:
                type: boolean
              foundationDate:
                type: string
              address:
                type: object
              confidence:
                type: number
          reasoning:
            type: string
          confidence:
            type: number
            minimum: 0
            maximum: 1
      confidence:
        type: number
      uiRequests:
        type: array
      error:
        type: string
    required: [status, contextUpdate]

tools:
  - secretary_of_state_lookup
  - business_registry_api
  - entity_verification_service
  - industry_classification_api

examples:
  business_discovery_example:
    input: "Discover information for Acme Corp LLC in California"
    output:
      status: completed
      contextUpdate:
        operation: business_discovered
        data:
          businessName: "Acme Corp LLC"
          entityType: "LLC"
          state: "CA"
          industry: "Technology Services"
          ein: "12-3456789"
          registrationStatus: "Active"
          goodStanding: true
          confidence: 0.92
        reasoning: "Successfully discovered business information through Secretary of State database lookup"
        confidence: 0.92