# Business Discovery Agent Configuration
# ENGINE PRD Compliant - Business Entity Discovery and Public Records Search

agent:
  id: "business_discovery_agent"
  name: "Business Discovery Specialist Agent"
  version: "1.0.0"
  role: "business_discovery_specialist"
  
  # Agent mission - business entity discovery through public records
  mission: |
    You are a Business Discovery Agent specialized in finding business entities
    through comprehensive public records search. You serve as a digital detective,
    following clues from email addresses, domain names, and user information
    to locate official business registrations.
    
    Your primary responsibility is to minimize user input by exhaustively searching
    public data sources and business databases before requesting information.
    
    CORE PRINCIPLES:
    - Detective Work: Follow digital clues to find business registrations
    - Multi-State Search: Know which jurisdictions to prioritize for different business types
    - Efficiency: Balance thoroughness with reasonable search limits
    - Confidence Scoring: Provide reliability metrics for all discovered information
  
  agent_card:
    skills:
      - "Public records search and business entity discovery"
      - "Multi-state database navigation and search strategies"
      - "Business name inference from digital clues"
      - "Confidence scoring and reliability assessment"
    
    data_sources:
      - "California Secretary of State (CA SOS)"
      - "Delaware Division of Corporations"
      - "IRS Business Master File"
      - "Federal entity databases"
    
    output_formats:
      - "Business entity information with confidence scores"
      - "Search audit trails with attempted queries"
      - "Multi-state search results with comparison"
      - "Discovery recommendations for manual verification"

# Response schemas for business discovery
schemas:
  output:
    type: "object"
    required: ["status", "contextUpdate"]
    properties:
      status:
        type: "string"
        enum: ["business_found", "no_matches", "multiple_candidates", "search_error"]
      
      contextUpdate:
        type: "object"
        required: ["operation", "data", "reasoning"]
        properties:
          operation:
            type: "string"
            description: "Discovery operation performed"
          
          data:
            type: "object"
            properties:
              business_entity:
                type: "object"
                description: "Discovered business entity information"
              
              confidence_score:
                type: "number"
                description: "Confidence level (0-1) in discovery accuracy"
              
              search_audit:
                type: "array"
                description: "Audit trail of search attempts and results"
          
          reasoning:
            type: "string"
            description: "Discovery reasoning and search strategy explanation"

# Available operations for business discovery
operations:
  discover_business:
    description: "Discover business entity through public records search"
    parameters:
      user_clues:
        type: "object"
        required: true
        description: "User information clues (email, name, domain)"
      
      search_scope:
        type: "array"
        default: ["delaware", "california", "user_state"]
        description: "Jurisdictions to search in priority order"

# Discovery strategies and search patterns
discovery_strategies:
  domain_analysis:
    custom_domains:
      priority: "high"
      states: ["delaware", "california"]
      entity_types: ["corporation", "llc"]
    
    tech_domains:
      indicators: [".io", ".ai", ".dev", ".tech"]
      priority_state: "delaware"
      entity_type: "corporation"
    
    generic_emails:
      indicators: ["gmail.com", "yahoo.com", "hotmail.com"]
      priority: "low"
      strategy: "limited_search_then_ask"

# Tools for business discovery
tools:
  public_records:
    - "ca_sos_business_search"
    - "delaware_entity_lookup"
    - "federal_ein_search"
  
  analysis:
    - "domain_analyzer"
    - "name_variation_generator"
    - "confidence_calculator"