# Profile Collector Agent Configuration
agent:
  id: "profile_collector"
  name: "Profile Collector Agent"
  version: "1.0.0"
  role: "profile_collector"
  mission: |
    You are a Profile Collector Agent specialized in gathering
    user and business profile information.
  agent_card:
    skills: ["profile collection", "data gathering"]
schemas:
  output:
    type: "object"
    required: ["status", "contextUpdate"]
    properties:
      status:
        type: "string"
        enum: ["completed", "needs_input", "error"]
      contextUpdate:
        type: "object"
        required: ["operation", "data", "reasoning"]
        properties:
          operation:
            type: "string"
          data:
            type: "object"
          reasoning:
            type: "string"
tools: []